directory = "_maps/map_files/solitairestation/modular_pieces/"

[rooms.cmo_office]
modules = ["cmo_office_1.dmm", "cmo_office_2.dmm", "cmo_office_3.dmm"]

[rooms.psychology]
modules = ["psychology_1.dmm", "psychology_2.dmm"]

[rooms.surgery]
modules = ["surgery_1.dmm", "surgery_2.dmm"]

[rooms.lawyer_office]
modules = ["law_office_1.dmm", "law_office_2.dmm", "law_office_3.dmm"]
